#from python lambda
FROM public.ecr.aws/lambda/python:3.8

# Install dependencies(reqirements.txt)
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY ./ ./

# Run the application
CMD [ "stories.lambda_handler" ]

